#ifeq ($(findstring 86, $(ProgramFiles)), )
#	PROGFILES := D:
#else
	PROGFILES := D:
#endif

GNU_INSTALL_ROOT := $(PROGFILES)/GNU Tools ARM Embedded/4.9 2015q1
GNU_VERSION := 4.9.3
GNU_PREFIX := arm-none-eabi

